version: '3'

services:
  postgresgqldb:
    image: postgres:latest
    restart: always
    container_name: postgres-gql-db-container
    ports:
      - '5871:5432'
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/scripts.sql
    environment:
      POSTGRES_USER: postgres-gql
      POSTGRES_PASSWORD: postgres-gql
      POSTGRES_DB: postgres-gql